### ISSUE TITLE
Path plots disappearing after outlier correction

### ISSUE THREAD

**Issue by petroskaramanides** [sgoldenlab/simba#488]
**Describe the bug**
When using the visualization tool to create path plots after having done outlier correction, some of the path plots show up as blank (i.e. there is no trace of animal movement in the arena).

**To Reproduce**
1. go to "outlier correction" tab
2. click "settings"
3. fill out with location and movement correction values (ex. 15/1.5, 10/1, 2.5/15)
4. body part 1 = nose; body part 2 = center; aggregation method = mean
5. click "run outlier correction"
6. go to "visualizations" tab
7. click "visualize paths"
8. in the pop-up window, click "include ROIs"
9. body-part 1: nose
10. click "create multiple videos (x video(s) found)"
11. check path plots in "output" folder of project to see if all path plots look "normal" and without outlier points

**Expected behavior**
I anticipate the outlier points (aberrant path plot points outside of the arena) to be removed, leaving only the animal's actual path in the arena.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.11.7
 - Using anaconda
 

**Additional context**
Seemingly no matter what location/movement outlier correction parameters are used, the result is unsatisfactory. If the movement correction is too high (<1.5), outlier points aren't removed. If it's too low (1.5>), a couple of the trials' path plots disappear altogether.

**Comment by sronilsson** [comment]
Hey @petroskaramanides - I think I understand thanks for the background. For some videos, either too many/too few movements are corrected through outlier correction and it's not possible to find suitable outlier criteria. 

For some offending video examples, would you mind sharing the CSV files as they are stores in the `project_folder/csv/input_csv` directory and I can take a look how the pose looks like? Could it be that the pose is just particularly bad in these videos, and improving the pose in these videos through better model/analysis in the pose-estimation package  solves it? 

How does it look if you interpolate (and possibly smooth) the pose-estimation imported to SimBA (and skip the outlier correction) ?

**Comment by petroskaramanides** [comment]
Hi, attached is an example csv for one of the path plots that seems to disappear.

[Trial     3_sSLR_sample_A2_6464.csv](https://github.com/user-attachments/files/23456760/Trial.3_sSLR_sample_A2_6464.csv)

Looks like the first few rows have zeroes, which might be leading to the difficulty?

For the interpolation/smoothing option, would I have to do that at the beginning of the simba project? As far as I'm aware, the interpolation is not post-processing. If that's the case, the solution would be to redo the projects and do interpolation at the beginning when I import the csvs and videos?

Thanks,

Petros

**Comment by sronilsson** [comment]
Hi @petroskaramanides - I don't think it is the missing body-parts in the beginning, but it's possible that the missing body-parts here-and-there is skewing SimBA's calculation of the mean/median animal length, which is then snowballing into messing up the outlier detections... 

Once you load the SimBA project, there is a button that allows interpolation of data within any of the `project_folder/csv` sub-directories or files. I would run that using the default settings on the `project_folder/csv/input_csv` directory. 

<img width="1692" height="812" alt="Image" src="https://github.com/user-attachments/assets/7518fc21-4570-4084-ba5a-ddafade7ace3" />

There is also an option to performing smoothing in the same fashion using the button immediately below. 

<img width="1468" height="625" alt="Image" src="https://github.com/user-attachments/assets/fc955644-b081-4f96-9fef-fedf45e5b3bd" />

However, I would just start with the interpolation of body-parts using nearest setting, and see if that is sufficient first. 

Once that is done, click skip outlier correction and see if the plots look better. Let me know if that makes sense or not or how it goes. 

PS. 

There is a further option in the SimBA toolbar screenshotted below and described [HERE](https://github.com/sgoldenlab/simba/blob/master/docs/Tutorial_tools.md#visualize-pose-estimation-in-folder) that I often use to help me visualize the pose in any SImBA data directory to understand how the pose has been affected by any outlier correction/smoothing/interpolation applied. 


<img width="1167" height="596" alt="Image" src="https://github.com/user-attachments/assets/214eacdd-557b-49a7-ad9a-33f5cfa42cf4" />

**Comment by petroskaramanides** [comment]
Hi again,

First just wanted to say the interpolation is working really well for my data and has cleaned up all of the outlier points so far, so thank you. One question though: I notice in the main SimBA page where you load projects, process videos, etc., it tells me when interpolating how many body parts are being interpolated for each video (ex. "interpolating 40 left ear body-parts for animal...). Some of the body part interpolations get quite high such as 40 or 63 when I feel like not that many frames are missing from the pose estimation data, though the resulting path plots (after I did interpolation and skipped outlier correction) look fine. Is this ok that the numbers seem kind of high? Why are so many body parts being interpolated? 

Also, for your linked directions on the "visualize pose estimation data" (your [link](https://github.com/sgoldenlab/simba/blob/master/docs/Tutorial_tools.md#visualize-pose-estimation-in-folder)), I think the directions are a bit out of date because the window looks different. I see options like "keypoint sizes" and "save directory" under "settings" and a "select data directory" option under "visualize data directory." Not sure if it's the same process, but I didn't know which options corresponded to the older window.

Thank you,

Petros

**Comment by petroskaramanides** [comment]
Update: now with some of the data I am still experiencing issues with outlier points even after the interpolation step. What I have found is that interpolation has done a great job at removing the (0,0) points at the top left of the path plots, but it's not as good at removing outlier points from elsewhere on the path plot.

**For example:**
NOT interpolated:
<img width="406" height="611" alt="Image" src="https://github.com/user-attachments/assets/2c083894-5bec-407a-b237-ec03126ffdb5" />

Interpolated (outlier correction skipped):
<img width="393" height="590" alt="Image" src="https://github.com/user-attachments/assets/63e98455-0b8f-4f88-afe0-0d03f407bb4d" />

Then, to try and fix this, I went with outlier correction on top of the interpolation. I tried settings such as location correction=3 and movement correction=1. Unfortunately, this had a deleterious effect on some of the path plots, removing too much data.

**For example:**
NOT interpolated or outlier corrected:
<img width="397" height="597" alt="Image" src="https://github.com/user-attachments/assets/6a516d8d-28ee-4c1a-afdb-9927c267b939" />

Interpolated + outlier correction (loc. = 5, mov. = 1):
<img width="396" height="592" alt="Image" src="https://github.com/user-attachments/assets/b804f88f-91f3-45e5-baad-50e9419876cf" />

Now I'm not sure if this is because I am putting in the wrong outlier correction values, but I am not sure what to do now. My workflow has been load data-->interpolate-->outlier correction-->visualize. Is there a place for smoothing to help this? Or to change my strategy so the plots are without outliers and don't lose any actual tracking? I would appreciate any help.

- Petros

**Comment by sronilsson** [comment]
Hey @petroskaramanides - thanks for letting me know. 

Looking at the CSV you shared earlier, the videos are about 15k frames, a body-part missing in 50-100 frames is not a lot and you should be good. Scrolling through that file, any body-part in a frame where the coordinates and confidence is et to `0` will be interpolates, e.g., the nose in frames 9090-9092: 

<img width="346" height="110" alt="Image" src="https://github.com/user-attachments/assets/3281f70d-fea1-466e-b32b-04e7b13c3e23" />

That said, if you still wanted to reduce the number of interpolated points, the way is to go back to the pose-estimation tool and improve the pose-estimation model so that it provides you data for the frames it currently cannot provide data for. That would involve annotating body-parts in select frames it cannot currently predict successfully on and retraining the models with those additional annotations. 

And thanks for the note on the docs, I will update it. The biggest challenge has been to keep docs, tutorials updated as the GUI and code base evolves.. so I tend to limit myself to update the docs when there iis reported issues...

**Comment by sronilsson** [comment]
Thanks @petroskaramanides .

In this video, my interpretation is that is something outside the circular arena, on the floor or table or whatever in the background, that is mistaken as the animal body-part for a few frames: 

<img width="371" height="343" alt="Image" src="https://github.com/user-attachments/assets/3032c7d7-18e0-4743-b550-016735fa425b" />

In future, these can be avoided by cropping the videos so as little of the background is viewed as possible before performing pose estimation and not allowing the pose model to do these mistakes. 

You could try to performing smoothing over say  250-500ms AFTER performing interpolation as described above in [this](https://private-user-images.githubusercontent.com/34761092/512257034-fc955644-b081-4f96-9fef-fedf45e5b3bd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI5NjMxMTEsIm5iZiI6MTc2Mjk2MjgxMSwicGF0aCI6Ii8zNDc2MTA5Mi81MTIyNTcwMzQtZmM5NTU2NDQtYjA4MS00Zjk2LTlmZWYtZmVkZjQ1ZTViM2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTEyVDE1NTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZTRmZmFhNTQ4ZTRjMjE5ZDkyYjMyODY5MzhlNjkzZTRmZTBiODM2NmFmMGY0Mzc4YzUyNzkzNGQwZTkzMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D5vr0B1HSuY23FjlzAkDDjT1_IGnXmJMjHBrmiVGycg) screengrab (and skip outlier correction) - does that improve it?

**Comment by petroskaramanides** [comment]
Hi again,

I tried performing the smoothing over both 250ms and 500ms after interpolation (skipped outlier correction), but it still looks like this:

![Image](https://github.com/user-attachments/assets/c3ca0e14-c1bd-4333-9e3a-b2e84959c24c)

I'm not sure what I can do now other than possibly just go back to the pose estimation model and try re-running it to get less of these aberrant frames?

Thanks again for all your help.

**Comment by sronilsson** [comment]
Hey @petroskaramanides  thanks for testing. 

Yes - just one concern if the smoothing has been done correctly. I am looking at the initial image (w/o smoothing) and comparing it to the image with smoothing, and the paths look almost identical. This makes me think that the two images may have been created from the un-smoothened data? 

<img width="894" height="476" alt="Image" src="https://github.com/user-attachments/assets/20c98464-c7fb-421c-a519-b73d7d40392c" />

The path plots are created from the `project_folder/csv/outlier_corrected_movement_location` directory (if you are **not** plotting classifications, which I don't think you do).

Did you smooth the data in the  `project_folder/csv/outlier_corrected_movement_location`  directory? Instead, if you smoothened the data in the `project_folder/csv/input_csv` directory, did you click to `SKIP OUTLIER CORRECTION` again after smoothing the data so that the new data was copied to the  `project_folder/csv/outlier_corrected_movement_location`  directory?

**Comment by petroskaramanides** [comment]
Yes what I did was interpolate-->smoothing (either 250 or 500 and either Gaussian or Savitzky Golay for 4 total combinations)-->skip outlier correction. The directory I used for the smoothing was pre_nearest_body-parts_interpolation_... is this the directory for the interpolated data? Or the original input.csvs? Because the pre_ suffix makes it seem like it is before interpolation, but if that's the case, I don't know where to locate the interpolated csvs.

**Comment by sronilsson** [comment]
Hey @petroskaramanides. 

The CSV files in the chosen directory gets **over-written** with the new, interpolated (or smoothened) data. 

So, if you choose to interpolate the data in `project_folder/csv/input_csv`, the interpolated data is saved in  `project_folder/csv/input_csv`. 

A copy of the un-interpolated (or un-smoothened), original, data is saved for in the "pre"-prefixed directory (for reference only) if `SAVE ORGININALS` has been chosen. 

Does that make sense? I can make this clearer with some tool-tips.

**Comment by petroskaramanides** [comment]
Ah ok that makes sense. Unfortunately, after now trying that method (using the input_csv directory, which is the interpolated version) and then skipping outlier correction, there are still 3 out of 19 path plots that have a couple outlier points outside the arena. None of these points are at (0,0) but are up and to the right though not all the way up or to the right (similar to the images I provided before).

It is possible that something outside the arena was detected as the animal during pose estimation, and I'm not sure that can be easily fixed with cropping after the SimBA project has been made, the ROIs have been drawn, etc. Is this an accurate interpretation?

**Comment by sronilsson** [comment]
Yeah, I would try one more thing -> smoothing -> interpolation -> some outlier correction. 

If that still fails, I would test:

1) crop the 3 videos, 2) analyze the cropped videos in the pose estimation tool again, 3) import the new pose-estimation data with the new (cropped videos) again into the same project (overwriting the 3 old CSV), 4) do-do the ROIs and  plotting for the 3 videos. 

  
<img width="558" height="563" alt="Image" src="https://github.com/user-attachments/assets/a37a2d05-4f41-4f57-8779-78d5f12caa72" />
